Add Cryptopro DSS sign method
fr05t1k/esia pull request #24
Opened 2019-12-06 09:02 UTC by cmpayc

Add signer to config
Add additionalData to config
Update config

2019-12-06 14:36 UTC, cmpayc commented
У некоторых ИС все сертификаты хранятся на внутреннем защищенном КриптоПро DSS сервере.
Все закрытые ключи и сертификаты хранятся на нем. Подписывать запрос и документы возможно только через REST API этого сервера.
ЕСИА умеет работать с ГОСТ подписями (2010, 2012), созданными при помощи КриптоПро DSS.

Добавленный метод проводит авторизацию через OAuth на КриптоПро DSS сервере и затем получает у сервера отсоединенную подпись для созданного запроса.

2019-12-11 19:53 UTC, fr05t1k requested changes
Можете тестов на класс SignerCryptoProDSS добавить?

2019-12-11 19:53 UTC, fr05t1k commented on src/Esia/OpenId.php
> +        $signer = 'Esia\\Signer\\' . $config->getSigner();
Для дополнительных Signer есть отдельный setter (setSigner) в этом классе. AdditionalData в этом случае будет не нужна, если  Signer будет передан как зависимость в setter. Вы можете передать всю необходимые настройки непосредственно в Signer.

2019-12-11 19:53 UTC, fr05t1k commented on src/Esia/Signer/SignerCryptoProDSS.php
> +        $client = new GuzzleHttpClient(new Client([
Нужно дать возможность использовать свой http клиент. 

https://github.com/fr05t1k/esia/blob/85f73132480038283363907b2216d14f4841632b/src/Esia/OpenId.php#L54

2019-12-11 19:54 UTC, fr05t1k commented
Спасибо за PR 👍

2024-10-20 11:49 UTC, closed without merging