Получение информации об организациях пользователя
fr05t1k/esia pull request #29
Opened 2020-04-12 18:27 UTC by shahruslan

Раньше информацию можно было получить одним запросом. Теперь нужно использовать два запроса. В первом запросе получаем идентификаторы организаций, а во втором уже непосредственно данные. Конечно, если заранее знать идентификатор организации, можно обойтись и одним запросом.
На тестовых аккаунтах работает без ошибок, на боевых пока проверить не смог.

2020-04-13 06:05 UTC, fr05t1k requested changes

2020-04-13 06:05 UTC, fr05t1k commented on src/Esia/OpenId.php
> +        $this->refreshToken($scopes);
А для чего обновлять токен при запросе организации?

2020-04-13 06:05 UTC, fr05t1k commented on src/Esia/OpenId.php
> +            return "http://esia.gosuslugi.ru/{$scope}?org_oid={$orgId}";
Тут наверно должно было использовано свойство `$portalUrl`

2020-04-13 06:52 UTC, shahruslan commented on src/Esia/OpenId.php
> +        $this->refreshToken($scopes);
Для того, чтобы передать скоуп вида http://esia.gosuslugi.ru/org_inn?org_oid=#ид_организации_который_нам_заранее_не_известен#
этот идентификатор мы получаем только после получения списка организаций. И если мы не обновим токен, то мы не можем запросить инн(например) организации, потому что скоуп org_inn не передан при первом обращении. При обновлении токена, мы передаем новые скоупы, по которум уже сможем получить данные организации.
Как я и написал выше, если идентификатор заранее известен, то можно обойтись и одним запросом, без обновления токена. Но этот случай очень редкий.

2020-04-13 06:58 UTC, shahruslan commented on src/Esia/OpenId.php
> +            return "http://esia.gosuslugi.ru/{$scope}?org_oid={$orgId}";
Нет, валидный скоуп именно такой, должен начинаться  с http://esia.gosuslugi.ru/
Если мы будем передавать `$portalUrl`, то на тестовом стенде ЕСИА это не сработает, потому как там `$portalUrl` отличается.

2020-04-13 07:12 UTC, fr05t1k commented on src/Esia/OpenId.php
> +            return "http://esia.gosuslugi.ru/{$scope}?org_oid={$orgId}";
Может вынести в константу?

2020-04-13 07:15 UTC, fr05t1k commented on src/Esia/OpenId.php
> +        $this->refreshToken($scopes);
Странно, а разве пользователь не должен дать согласие на получение данных из другого скоупа, нежели был изначально запрошен при получение токена? Есть ссылка на документацию где можно почитать об этом?

2020-04-13 07:16 UTC, fr05t1k commented
Ну и не плохо было бы покрыть тестами методы `refreshToken`, `getOrganizationLinks`, `getOrganizationInfo`

2020-04-13 07:17 UTC, shahruslan commented on src/Esia/OpenId.php
> +            return "http://esia.gosuslugi.ru/{$scope}?org_oid={$orgId}";
Да, можно.
А как лучше назвать, ESIA_URL ?)

2020-04-13 07:20 UTC, fr05t1k commented on src/Esia/OpenId.php
> +            return "http://esia.gosuslugi.ru/{$scope}?org_oid={$orgId}";
Можно думаю `SCOPE_DOMAIN`

2020-04-13 07:20 UTC, fr05t1k commented on src/Esia/OpenId.php
> +            return "http://esia.gosuslugi.ru/{$scope}?org_oid={$orgId}";
Или `SCOPE_URL`

2020-04-13 16:08 UTC, shahruslan commented on src/Esia/OpenId.php
> +        $this->refreshToken($scopes);
Да, странно. Если передать скоуп вида `http://esia.gosuslugi.ru/org_inn?org_oid=123` при первом запросе на получение авторизационного кода, то да, запрос на согласие предоставления инн организации появится. Но `org_oid` мы получаем только после того как запросим скоуп `usr_org`. Так что тут или еще раз сделать редирект на `$portalUrl`, но уже со скоупами организаций. Или вот таким способом. 

Документация вот https://digital.gov.ru/ru/activity/directions/13/#section-docs
Методические рекомендации ... Раздел В.3

2020-04-14 06:25 UTC, fr05t1k commented on src/Esia/OpenId.php
> +        $this->refreshToken($scopes);
А ты пробовал из пункта В.4?

![image](https://user-images.githubusercontent.com/2131624/79192617-ba297d80-7e31-11ea-9719-3cf4c87b6ed5.png)

2020-04-14 06:52 UTC, shahruslan commented on src/Esia/OpenId.php
> +        $this->refreshToken($scopes);
Да, пробовал. Там возвращаются не все данные, а только этот набор из списка. Другие данные вытащить не получалось.

2026-08-10 01:23 UTC, fr05t1k commented
Спасибо за вклад! 🙏 Получение информации об организациях пользователя теперь консолидировано в roadmap-задаче #75 (вместе с #43 и #63) в рамках эпика #77. Закрываю в пользу единой реализации с тестами; ваш подход учтём. / Thanks — superseded by the consolidated issue #75 (epic #77).

2026-08-10 01:23 UTC, closed without merging